[project]
name = "ai4bharat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.5.0",
    "dotenv>=0.9.9",
    "huggingface-hub>=1.4.1",
    "unsloth-mlx>=0.3.5",
]
